kind: Deployment
apiVersion: apps/v1
metadata:
  name: easy-ws-mock-pet-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: easy-ws-mock-pet-store
      app.kubernetes.io/name: easy-mock-ws
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: easy-ws-mock-pet-store
        app.kubernetes.io/name: easy-mock-ws
    spec:
      volumes:
        - name: easy-ws-mock-pet-store-volume
          configMap:
            name: easy-ws-mock-pet-store-cm
            items:
              - key: definitions.json
                path: definitions/definitions.json
              - key: defaultResponse
                path: responses/WsIngestionService/defaultResponse
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: ws-mock
          securityContext: {}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: easy-ws-mock-pet-store-volume
              mountPath: /etc/mocks
          terminationMessagePolicy: File
          image: 'saiello/easy-mock-ws:0.0.1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600